apiVersion: apps/v1
kind: Deployment
metadata:
  name: udu-backend-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: udu-backend
  template:
    metadata:
      labels:
        app: udu-backend
    spec:
      containers:
      - name: udu-backend
        image: اسم-صورة-الباك-اند:إصدار
        ports:
        - containerPort: 8080

---
apiVersion: v1
kind: Service
metadata:
  name: udu-backend-service
spec:
  selector:
    app: udu-backend
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
  type: ClusterIP
