apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend-nginx-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: backend-nginx
  template:
    metadata:
      labels:
        app: backend-nginx
    spec:
      containers:
      - name: backend-nginx
        image: backend-nginx:v1
        ports:
        - containerPort: 80

---
apiVersion: v1
kind: Service
metadata:
  name: backend-nginx-service
spec:
  selector:
    app: backend-nginx
  type: LoadBalancer
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
